** ComfyUI startup time: 2024-02-27 12:00:56.314314
[2024-02-27 12:00] ** Platform: Windows
[2024-02-27 12:00] ** Python version: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
[2024-02-27 12:00] ** Python executable: C:\Python310\python.exe
[2024-02-27 12:00] ** Log path: C:\Users\Lightmapper\Documents\GitHub\ComfyUI\comfyui.log
[2024-02-27 12:00] 
Prestartup times for custom nodes:
[2024-02-27 12:00]    0.0 seconds: C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\rgthree-comfy
[2024-02-27 12:00]    0.0 seconds: C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\ComfyUI-Manager
[2024-02-27 12:00] 
[2024-02-27 12:00] Total VRAM 24576 MB, total RAM 65451 MB
[2024-02-27 12:00] Set vram state to: NORMAL_VRAM
[2024-02-27 12:00] Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
[2024-02-27 12:00] VAE dtype: torch.bfloat16
[2024-02-27 12:00] Using pytorch cross attention
[2024-02-27 12:00] ### Loading: ComfyUI-Manager (V2.8.3)
[2024-02-27 12:00] 

## [WARN] ComfyUI-Manager: Your ComfyUI version (1892)[2024-01-09] is too old. Please update to the latest version. ##

[2024-02-27 12:00] 
[2024-02-27 12:00] ### ComfyUI Revision: 1892 [b3ef363f] | Released on '2024-01-09'
[2024-02-27 12:00] [0;33m[ReActor][0m - [38;5;173mSTATUS[0m - [0;32mRunning v0.4.1-b11 in ComfyUI[0m
[2024-02-27 12:00] Traceback (most recent call last):
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\nodes.py", line 1814, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 23, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 15, in <module>
    from scripts.reactor_faceswap import (
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_faceswap.py", line 13, in <module>
    from scripts.reactor_logger import logger
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_logger.py", line 6, in <module>
    from reactor_utils import addLoggingLevel
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\comfyui-reactor-node\reactor_utils.py", line 8, in <module>
    from insightface.app.common import Face
ModuleNotFoundError: No module named 'insightface'
[2024-02-27 12:00] 
[2024-02-27 12:00] Cannot import C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: No module named 'insightface'
[36;20m[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts[0m
[2024-02-27 12:00] [36;20m[comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
[2024-02-27 12:00] [36;20m[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
[2024-02-27 12:00] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[2024-02-27 12:00] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[2024-02-27 12:00] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[2024-02-27 12:00] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[2024-02-27 12:01] Traceback (most recent call last):
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\nodes.py", line 1814, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\__init__.py", line 24, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\nodes.py", line 5, in <module>
    from usdu_patch import usdu
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\usdu_patch.py", line 2, in <module>
    from repositories import ultimate_upscale as usdu
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\__init__.py", line 14, in <module>
    spec.loader.exec_module(ultimate_upscale)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 4, in <module>
    from modules import processing, shared, images, devices, scripts
ImportError: cannot import name 'devices' from 'modules' (C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\comfyui-reactor-node\modules\__init__.py)
[2024-02-27 12:01] 
[2024-02-27 12:01] Cannot import C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale module for custom nodes: cannot import name 'devices' from 'modules' (C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\comfyui-reactor-node\modules\__init__.py)
[2024-02-27 12:01] 
[2024-02-27 12:01] [92m[rgthree] Loaded 35 exciting nodes.[0m
[2024-02-27 12:01] [92m[rgthree] Will use rgthree's optimized recursive execution.[0m
[2024-02-27 12:01] 
[2024-02-27 12:01] 
Import times for custom nodes:
[2024-02-27 12:01]    0.0 seconds: C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\sdxl-recommended-res-calc
[2024-02-27 12:01]    0.0 seconds: C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\tiled_ksampler
[2024-02-27 12:01]    0.0 seconds: C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\rgthree-comfy
[2024-02-27 12:01]    0.0 seconds (IMPORT FAILED): C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
[2024-02-27 12:01]    0.0 seconds (IMPORT FAILED): C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\comfyui-reactor-node
[2024-02-27 12:01]    0.3 seconds: C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\ComfyUI-Manager
[2024-02-27 12:01]    0.8 seconds: C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\comfyui_controlnet_aux
[2024-02-27 12:01] 
[2024-02-27 12:01] Starting server
[2024-02-27 12:01] 
[2024-02-27 12:01] To see the GUI go to: http://127.0.0.1:8188
[2024-02-27 12:01] got prompt
[2024-02-27 12:01] Error handling request
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "C:\Python310\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
  File "C:\Python310\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\server.py", line 47, in cache_control
    response: web.Response = await handler(request)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\server.py", line 474, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\execution.py", line 615, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'Eff. Loader SDXL'
[2024-02-27 12:04] got prompt
[2024-02-27 12:04] Error handling request
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "C:\Python310\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
  File "C:\Python310\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\server.py", line 47, in cache_control
    response: web.Response = await handler(request)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\server.py", line 474, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\execution.py", line 615, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'Text box'
[2024-02-27 12:04] got prompt
[2024-02-27 12:04] Error handling request
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "C:\Python310\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
  File "C:\Python310\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\server.py", line 47, in cache_control
    response: web.Response = await handler(request)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\server.py", line 474, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\execution.py", line 615, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'Text box'
[2024-02-27 12:33] got prompt
[2024-02-27 12:33] Error handling request
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "C:\Python310\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
  File "C:\Python310\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\server.py", line 47, in cache_control
    response: web.Response = await handler(request)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\server.py", line 474, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\execution.py", line 615, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'Text box'
[2024-02-27 12:34] got prompt
[2024-02-27 12:34] Error handling request
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "C:\Python310\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
  File "C:\Python310\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\server.py", line 47, in cache_control
    response: web.Response = await handler(request)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\server.py", line 474, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\execution.py", line 615, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'Text box'
[2024-02-27 12:34] got prompt
[2024-02-27 12:34] Error handling request
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "C:\Python310\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
  File "C:\Python310\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\server.py", line 47, in cache_control
    response: web.Response = await handler(request)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\server.py", line 474, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\execution.py", line 615, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'Text box'
[2024-02-27 12:34] got prompt
[2024-02-27 12:34] Error handling request
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "C:\Python310\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
  File "C:\Python310\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\server.py", line 47, in cache_control
    response: web.Response = await handler(request)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\server.py", line 474, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\execution.py", line 615, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'Text box'
[2024-02-27 12:34] got prompt
[2024-02-27 12:34] Error handling request
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "C:\Python310\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
  File "C:\Python310\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\server.py", line 47, in cache_control
    response: web.Response = await handler(request)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\server.py", line 474, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\execution.py", line 615, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'Text box'
[2024-02-27 12:34] got prompt
[2024-02-27 12:34] Error handling request
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "C:\Python310\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
  File "C:\Python310\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\server.py", line 47, in cache_control
    response: web.Response = await handler(request)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\server.py", line 474, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\execution.py", line 615, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'Text box'
[2024-02-27 12:35] FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[2024-02-27 12:35] Start fetching...[2KFetching: C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\ComfyUI-Manager[2KFetching: C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\comfyui_controlnet_aux[2KFetching: C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale[2KFetching: C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\comfyui-reactor-node[2KFetching: C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\rgthree-comfy[2KFetching: C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\sdxl-recommended-res-calc[2KFetching: C:\Users\Lightmapper\Documents\GitHub\ComfyUI\custom_nodes\tiled_ksampler[2KFetching done.
[2024-02-27 12:35] got prompt
[2024-02-27 12:35] Error handling request
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "C:\Python310\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
  File "C:\Python310\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\server.py", line 47, in cache_control
    response: web.Response = await handler(request)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\server.py", line 474, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "C:\Users\Lightmapper\Documents\GitHub\ComfyUI\execution.py", line 615, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'Text box'
[2024-02-27 12:36] FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[2024-02-27 12:36] FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
